accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
     url(r'^login/$', views.ELoginView.as_view(), name='login'),
]

c3d/urls.py
# from django.contrib import admin
# from django.urls import path
# from django.conf.urls import include, url
#
# from accounts.views import ELoginView    # Представление для авторизации из модуля accounts
#
# urlpatterns = [
#     url(r'^$', include('c3d_site_app.urls')),
#     url(r'^admin/login/', ELoginView.as_view()),
#     url(r'^admin/', admin.site.urls),
#     url(r'^accounts/', include('accounts.urls')),    # также добавим url модуля авторизаций
# ]

from django.conf.urls import url, include
from django.contrib import admin

from accounts.views import ELoginView  # Представление для авторизации из модуля accounts

# Чтобы перехватить страницу авторизации, необходимо
# прописать путь к этой странице перед url админ-панели
# и указать представление, которое будет теперь обрабатывать авторизацию
urlpatterns = [
    url(r'^admin/login/', ELoginView.as_view()),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),  # также добавим url модуля авторизаций
    url(r'', include('c3d_site_app.urls')),
    ]

c3d_site_app/urls.py
from django.conf.urls import url


from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(\d+)/', views.post, name='post'),
    url('^category/(?P<category>[A-Za-z0-9]+)/$', views.category, name='category'),
    url(r'^categories/', views.categories, name='categories+'),
    url(r'^new/', views.new, name='name'),
]

accounts/models.py
from django.db import models

# Create your models here.

c3d_site_app/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.contenttypes.fields import GenericRelation

class Categories(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    def __str__(self):
        return self.title
    def __repr__(self):
        return self.title


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    text = models.TextField()
    category = GenericRelation(Categories)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    rate = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], default=0)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

c3d_site_app/forms.py
# В нем нужно написать:
from django import forms
from .models import Post
from .models import Categories

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author', 'title', 'text', 'rate', 'published_date')
# поля pub_date и id заполняются сами

accounts/views.py
from urllib.parse import urlparse

from django.shortcuts import redirect, render_to_response
from django.contrib import auth
from django.template.context_processors import csrf
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
# from .special_func import get_next_url


class ELoginView(View):

    def get(self, request):
        # если пользователь авторизован, то делаем редирект на главную страницу
        if auth.get_user(request).is_authenticated:
            return redirect('/')
        else:
            # Иначе формируем контекст с формой авторизации и отдаём страницу
            # с этим контекстом.
            # работает, как для url - /admin/login/ так и для /accounts/login/
            context = create_context_username_csrf(request)
            return render_to_response('accounts/login.html', context=context)

    def post(self, request):
        # получив запрос на авторизацию
        form = AuthenticationForm(request, data=request.POST)

        # проверяем правильность формы, что есть такой пользователь
        # и он ввёл правильный пароль
        if form.is_valid():
            # в случае успеха авторизуем пользователя
            auth.login(request, form.get_user())
            return redirect('/')

        # если данные не верны, то пользователь окажется на странице авторизации
        # и увидит сообщение об ошибке
        context = create_context_username_csrf(request)
        context['login_form'] = form

        return render_to_response('accounts/login.html', context=context)


# вспомогательный метод для формирования контекста с csrf_token
# и добавлением формы авторизации в этом контексте
def create_context_username_csrf(request):
    context = {}
    context.update(csrf(request))
    context['login_form'] = AuthenticationForm
    return context

c3d_site_app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from .models import Post
from .models import Categories
from .forms import PostForm
from django.shortcuts import redirect


# def index(request):
#     return HttpResponse("Любой текст")

def index(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    star = ''
    return render(request, 'c3d_site_app/index.html', {'posts': posts})

def post(request, p_id):
    f = Post.objects.get(id=p_id)
    return render(request, 'c3d_site_app/post.html', {'post_id': f, 'text': f.text})


def category(request, category):
    return render(request, "c3d_site_app/category.html", {"category": Categories.objects.get(title=category)})


def categories(request):
    return render(request, "c3d_site_app/categories.html", {"categories": Categories.objects.all})


def new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            add_post = form.save()
            return redirect('/')
    else:
        return render(request, 'c3d_site_app/new.html', {'new_post_form': PostForm()})

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
  <head>
     {% load bootstrap3 %}
     <script src="{% bootstrap_jquery_url %}"></script>
     {% bootstrap_javascript %}
    <title>Авторизация</title>
  </head>
  <body>

<form id="contact_form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form login_form %}
    {% buttons %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Войти</button>
        </div>
    {% endbuttons %}
</form>

  </body>
</html>

accounts/templates/accounts/login_widget.html
<!DOCTYPE html>
<html>
  <head>
    <title>Авторизация</title>
  </head>
  <body>
    <form id="contact_form" action="{% url 'accounts:login' %}" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit" class="btn btn-secondary">Войти</button>
    </form>
  </body>
</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Регистрация</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Зарегистрироваться</button>
    </form>
  </body>
</html>

c3d_site_app/templates/c3d_site_app/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Audiowide|Boogaloo|Open+Sans+Condensed:300" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>

</head>
<body>

<div>


    <!-- Image and text -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="font-family: 'Audiowide', cursive">
        <a class="navbar-brand" href="/">
            <img src={% static "c3d_site_app/penguin.jpeg" %} width="30" height="30" class="d-inline-block align-top"
            alt="">
            C3D
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
                </li>

            </ul>
            </a>
            <a href="/new/" class="btn btn-secondary">Добавить новый пост</a>
            &nbsp;&nbsp;
            {% include 'accounts/login_widget.html' %}

        </div>
    </nav>


    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: green">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/" style="color:white;">Главная <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/categories/" style="color:white;">Категории</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
            </form>
        </div>
    </nav>

</div>

<p></p>


<div class="content container">
    <div class="row">
        <div class="col-md-12">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>


<div style="background-color: green; color:white;">

    <div class="container">
        <div class="row">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                &copy; C3D
            </div>
            <div class="col-sm">

            </div>
        </div>
    </div>

</div>

</body>
</html>

c3d_site_app/templates/c3d_site_app/categories.html
{% extends "c3d_site_app/base.html" %}
{% load static %}
{% block title %}C3D - категории{% endblock %}
{% block content %}
{% for categories_ in categories %}
<div class="post">
    <h1><a href="/category/{{ categories_ }}">{{ categories_ }}</a></h1>
</div>
{% endfor %}
{% endblock %}

c3d_site_app/templates/c3d_site_app/category.html
{% extends "c3d_site_app/base.html" %}
{% load static %}
{% block title %}C3D - категория{% endblock %}
{% block content %}
<h1>{{ category }}</h1>
{% endblock %}

c3d_site_app/templates/c3d_site_app/index.html
{% extends "c3d_site_app/base.html" %}
{% load static %}
{% block title %}C3D{% endblock %}
{% block content %}
{% for post in posts %}
<div class="post">
    <div class="date">
        <p>Лайков: 0 <img src={% static "c3d_site_app/like.png" %} width="20" height="20"
            class="d-inline-block align-top" alt=""></p>
        <p>Рейтинг: {{ post.rate }} <img src={% static "c3d_site_app/star.jpg" %} width="20" height="20"
            class="d-inline-block align-top" alt=""></p>
        <p>Опубликовано: {{ post.published_date }}</p>
    </div>
    <h1><a href="post/{{ post.id }}">{{ post.title }}</a></h1>
    <p>{{ post.text|linebreaksbr }}</p>
    <p>Комментариев: 0 <img src={% static "c3d_site_app/comment.png" %} width="20" height="20"
        class="d-inline-block align-top" alt=""></p>
</div>
{% endfor %}
{% endblock %}

c3d_site_app/templates/c3d_site_app/new.html
{% extends "c3d_site_app/base.html" %}
{% load static %}
{% block title %}C3D - Написать пост{% endblock %}
{% block content %}
<center>

    <h1>Написать пост</h1>
    <form method="POST">{% csrf_token %}
        {{ new_post_form.as_p }}
        <button type="submit">Save</button>
    </form>
</center>
{% endblock %}

c3d_site_app/templates/c3d_site_app/post.html
{% extends "c3d_site_app/base.html" %}
{% load static %}
{% block title %}C3D{% endblock %}
{% block content %}
<div class="post">
    <h1><a href="">{{ post_id }}</a></h1>
    <p>{{ text|linebreaksbr }}</p>
</div>
{% endblock %}